force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>First_Name__c + &quot; &quot; +  Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Number_of_Expense_Reports__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Expense_Reports__c</fullName>
    <label>Number of Expense Reports</label>
    <summaryForeignKey>Expense_Report__c.Employee__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Total_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Expenses__c</fullName>
    <label>Total Expenses</label>
    <summarizedField>Expense_Report__c.Total_Amount_of_Expenses__c</summarizedField>
    <summaryForeignKey>Expense_Report__c.Employee__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>EI-{0000000}</displayFormat>
        <label>Expense Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expense_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Report__c/Expense_Report__c.object-meta.xml
<CustomObject>
    <label>Expense Report</label>
    <nameField>
        <displayFormat>ER-{YYMM}{00000}</displayFormat>
        <label>Expense Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Report__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Expense Reports</relationshipLabel>
    <relationshipName>Expense_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Report__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>Employee__r.Employee_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Report__c/fields/Number_of_Expense_Items__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Expense_Items__c</fullName>
    <label>Number of Expense Items</label>
    <summaryForeignKey>Expense_Item__c.Expense_Report__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Report Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Report__c/fields/Total_Amount_of_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Expenses__c</fullName>
    <label>Total Amount of Expenses</label>
    <summarizedField>Expense_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Expense_Item__c.Expense_Report__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/ExpensesController.cls
public with sharing class ExpensesController {
    
    @AuraEnabled(cacheable=true)
    public static Expense_Report__c[] getExpenseReports(String employeeId){
        try {
            if (employeeId == '') {
                return [
                SELECT Name, 
                        Employee__r.Employee_Name__c,
                        Report_Date__c, 
                        Number_of_Expense_Items__c, 
                        Total_Amount_of_Expenses__c
                FROM Expense_Report__c
                WITH SECURITY_ENFORCED
                ORDER BY NAME
            ];
            } else {
            return [
                SELECT Name, 
                        Employee__r.Employee_Name__c,
                        Report_Date__c, 
                        Number_of_Expense_Items__c, 
                        Total_Amount_of_Expenses__c
                FROM Expense_Report__c
                WHERE Employee__r.Id = :employeeId
                WITH SECURITY_ENFORCED
                ORDER BY NAME
            ];
        }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Employee__c[] getEmployeeList(){
        try {
            return [
                SELECT Id, Name, Employee_Name__c,
                Number_of_Expense_Reports__c,
                Total_Expenses__c
                FROM Employee__c
                WITH SECURITY_ENFORCED
                ORDER BY Name
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Employee__c[] searchEmployees(String searchTerm) {
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getEmployeeList();
        }

        searchTerm = '%' + searchTerm + '%';

        return [
            SELECT Id, Name, Employee_Name__c,
            Number_of_Expense_Reports__c,
            Total_Expenses__c
            FROM Employee__c
            WHERE Employee_Name__c LIKE :searchTerm
            WITH SECURITY_ENFORCED
            ORDER BY Name
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Expense_Item__c[] getExpenseItems(String reportId){
        try {
           return [
            SELECT Name, Category__c,
                Vendor__c, Amount__c
            FROM Expense_Item__c
            WHERE Expense_Report__r.Id = :reportId
            WITH SECURITY_ENFORCED
            ORDER BY NAME
        ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}